name: GitHub Actions Build and Deploy

# 触发条件: push 到 dev 分支后
on:
  workflow_dispatch:
  push:
    branches:
      - dev
    # 只在下列路径变更时触发
    paths:
      - 'docs/**'
      - 'package.json'

# 设置深圳时区
env:
  TZ: Asia/Shenzhen

# 任务
jobs:
  build-and-deploy:
    # 服务器环境：最新版 ubuntu
    runs-on: ubuntu-latest
    steps:
      # 拉取代码
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      # 安装 pnpm
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      # 设置 node 版本
      - name: Set node version to 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      # 打包静态文件
      - name: Build
        run: pnpm install && pnpm run build:github

      - name: Copy files
        run: cp README.md ./dist/

      # 部署
        - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          # GitHub 密钥
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          # 指定仓库
          REPOSITORY_NAME: raomaiping/map-demo
          # GitHub Pages 读取的分支
          BRANCH: gh-pages
          # 静态文件所在目录
          FOLDER: dist
